apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alert-watcher2-pdb
  namespace: default
  labels:
    app: alert-watcher2
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: alert-watcher2
