apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-watcher2
  namespace: default
  labels:
    app: alert-watcher2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-watcher2
  labels:
    app: alert-watcher2
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alert-watcher2
  labels:
    app: alert-watcher2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alert-watcher2
subjects:
- kind: ServiceAccount
  name: alert-watcher2
  namespace: default
